name: iTMUXiOSClient
options:
  bundleIdPrefix: com.itmux
packages:
  iTMUX:
    path: ..
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
targets:
  iTMUXiOSClient:
    type: application
    platform: iOS
    sources:
      - path: iTMUXiOSClient/Sources
    resources:
      - path: iTMUXiOSClient/Resources
    dependencies:
      - package: iTMUX
        product: iTMUX
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.itmux.client
        DEVELOPMENT_ASSET_PATHS: "\"iTMUXiOSClient/Resources/Preview Content\""
        TARGETED_DEVICE_FAMILY: "1,2"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UIRequiresFullScreen: NO
        SUPPORTS_MACCATALYST: NO
        CODE_SIGN_STYLE: Automatic
schemes:
  iTMUXiOSClient:
    build:
      targets:
        iTMUXiOSClient: all
    run:
      config: Debug
    archive:
      config: Release
